dist: xenial
sudo: false
install: true

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      services:
        - postgresql

      before_install:
        - cd backend
        - chmod +x mvnw

      script:
        - ./mvnw clean install -DskipTests=false -B

      dist: trusty

      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
          # all_branches: true
        app: pharmacy-tim9

    - language: node_js
      node_js:
      - "node"
      cache: npm
      script: 
        - cd frontend/pharmacy
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
          # all_branches: true
        app: pharmacy9