sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - cd backend
  - chmod +x mvnw

script:
  - ./mvnw clean install -DskipTests=false -B

dist: trusty

# after_success:
#   - cd ../
#   - git subtree push --prefix backend heroku master

before_deploy: "cd backend"

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: pharmacy-tim9
