dist: xenial
sudo: false
install: true

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      services:
        - postgresql

      before_install:
        - cd backend
        - mv src/main/resources/application.properties src/main/resources/application-local.properties
        - mv src/main/resources/application-deploy.properties src/main/resources/application.properties
        - chmod +x mvnw

      script:
        - ./mvnw clean install -DskipTests=false -B

      dist: trusty

      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          all_branches: true
        app: pharmacy-tim9

    - language: node_js
      node_js:
      - "node"
      cache: npm
      script: 
        - cd frontend/pharmacy
        - mv vue.config.js vue.config-local.js
        - mv vue.config-deploy.js vue.config.js
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          all_branches: true
        app: pharmacy9