dist: xenial
sudo: false
install: true

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      services:
        - postgresql

      before_install:
        - cd backend
        - chmod +x mvnw

      addons:
        sonarcloud:
          organization: isidora-stanic
          token: 
            secure: "IviL0xxl/cixUovRPQ4WLMaVbRWGHILl1Onwpp+D0WVwctsqefxfv0MeEJ3qHHeUuwvN9xLjNMsCTOFRGGgcgwsM4pR2+BgplHNwpUt8caECEkyP+KKFEI+hj/mbaAY/frvwm3ZskZVLM9clEaG/ci/4n46+W9c9si3651nPfcuZBIFbSI37NMy850aTl3zacq5QyNtEoRO1ijYsynGAY6PRaSkou7xNR0/cqNvEXzQMCJjmHKVyEfNomwziuIKlZLuGqBvYNMr1Pf6sCmTqdMgPE9Vwfx0guz+Odb+uqkQZX7s2jXdD+4ng0uEpvdm+7+4erdRgajmdgdIMmj8B3eFmQe/4SrrDYKvNaJ7OHnX4ds+AAmUCv3uR0YPAsbBso7DSYYrIGMjEHdIiKiZ0KG3xrNnc2LcKzkwnBe/08zKmD/RaAtROVFE5skhCznaQyAMt7r8JoocbHf+Tnb7rKoSjzNPbp/YycMFaXeLmt1P/6RIux1V5NNQRmcNLx90T98u17SoAHxlRrWR0f5VIhHor5+16dwzJ45blLoVTyP8+to/Q6+0zDD+fNJH+nf++3aelWx/lCC4RvKjgMPsYXFv5U64OtO0FByWsqw1O2j0DBdXcYa9+GQEauwUf8/PirlD8L/U9q7G+evNh5KmH0J8oT+1zmDSDSkZAP1kJqcI="

      script:
        - ./mvnw clean install -DskipTests=false -B
        - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=isidora-stanic
        # - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=mrs-isa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

      dist: trusty

      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
        app: pharmacy-tim9

    - language: node_js
      node_js:
      - "node"
      cache: npm
      script: 
        - cd frontend/pharmacy
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
        app: pharmacy9