dist: xenial
sudo: false
install: true

matrix:
  include:
    - language: java
      jdk: oraclejdk11
      services:
        - postgresql

      before_install:
        - cd backend
        - chmod +x mvnw

      addons:
        sonarcloud:
          organization: milospp
          token: 
            secure: "Mv/Xbbet1gVnUc8iUKeNuJ8q+Sro/2MffoJfyzMiqL6bGN7X07f+G/X9SDnWwGiTctN39uK8l2DQV+Xki4hAW2B9LyZzB+Y++qwKar8SewMh9zK+PwiZ0uKbXwcwbSpCPMAxbb21DLpkdwQD7GuaOCnRDiVmpjDi2FTKno0BzVwuYMrHwlWt6S7zcRGPQhE/c5v03PnzlLzBm0/1xCCppygA4+oSjLl1AhcXcF0qAiHsmznpRvYrsDBRSTk7BR/3hrQlXZoQBXFvN9HqZq+2NkwHSl8mMKIrg3SADYyIt9fwXZz5h44BCNdOA/s+uSQRkE3u1dv3djuiTbjzo7mTsjiKdAuYrresM5hUZEuLAggk0B+QQjjIPkksfxFrwvgnbtFDnXlF0kYP/BFyFEfrdwodQcYHEnqPSk0sGGgXjEEf7OzmsDQt2U4AgZKe3qGE1xZAHHRzni6v4YtxVxl2Ie/njCHgFIXqojk7KXt/Y1ncCbGXurw/9mlVBC+R61IstTUCXrSSuXtIXmMIWEAxsKRtkjp+YqdDVDuL/3bZgfn+tguSo3hzNtPMSWyjSRD89kMGza/O3aPU4u0Sjdkk5lslEHQQSgmja87mem9a7FCY/KGsehM8BV3W6K+tgKIu59yYaC0VEnWtQKvDiNa6AP5xbY26yi712O1Tm2H2PVI="

      script:
        - ./mvnw clean install -DskipTests=false -B
        - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=milospp_mrs-isa
        # - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=mrs-isa -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

      dist: trusty

      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
        app: pharmacy-tim9

    - language: node_js
      node_js:
      - "node"
      cache: npm
      script: 
        - cd frontend/pharmacy
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        on:
          branch: main
        app: pharmacy9