# sudo: required
# language: java
# jdk: oraclejdk11

# services:
#   - postgresql

# before_install:
#   - cd backend
#   - chmod +x mvnw

# script:
#   - ./mvnw clean install -DskipTests=false -B

# dist: trusty

# deploy:
#   provider: heroku
#   api_key: $HEROKU_API_KEY
#   on:
#     all_branches: true
#   app: pharmacy-tim9

language: node_js
node_js:
 - "node"


before_install:
  - cd frontend/pharmacy

cache: npm

script: npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  on:
    all_branches: true
  app: pharmacy9




# sudo: required
# language: vue_js

# script:
#   - cd frontend/pharmacy

# dist: trusty


# deploy:
#   provider: heroku
#   api_key: $HEROKU_API_KEY
#   on:
#     all_branches: true
#   app: pharmacy9
